title: GoRoutes
# email: voce@example.com
description: >-
  Um Sistema Para Gerenciamento de Rotas.

theme: jekyll-theme-cayman

# twitter_username: seuusuario
# github_username: seuusuario
# linkedin_username: seuusuario

plugins:
  - jekyll-feed
  - jekyll-seo-tag