title: GoRoutes
# email: voce@example.com
description: >-
  Um site simples e elegante usando o tema Minimal do Jekyll.

theme: jekyll-theme-minimal

# twitter_username: seuusuario
# github_username: seuusuario
# linkedin_username: seuusuario

plugins:
  - jekyll-feed
  - jekyll-seo-tag